#!/bin/bash

# Sweep QPS with mutilate --scan using FB/Meta ETC-style workload presets.
# Mirrors host layout in power-mut-xl170.sh but runs a single scan instead of a QPS loop.

set -euo pipefail

# === Configuration ===
SERVER_ALIAS="server_mem"
CLIENT1_ALIAS="client_mem1"
CLIENT2_ALIAS="client_mem2"
CLIENT3_ALIAS="client_mem3"   # also used as mutilate master

MEMCACHED_IP="10.10.1.1"
MEMCACHED_PORT=11211
MEMCACHED_THREADS=20
MEMCACHED_CORE_RANGE="0-19"
MEMCACHED_MAX_CONNECTIONS=50000

MUTILATE_AGENT_THREADS=12
MUTILATE_AGENT_CORE_RANGE="0-11"
MUTILATE_AGENT_CLIENTS=64
MUTILATE_AGENT_DEPTH=8
MUTILATE_TEST_DURATION=120
MUTILATE_WARMUP=30
MUTILATE_IADIST="exponential"    # Poisson arrivals
# fb_value   = a hard-coded discrete and GPareto PDF of value sizes
# fb_key     = "gev:30.7984,8.20449,0.078688", key-size distribution
MUTILATE_KEYSIZE="fb_key" # Follows ETC workload
MUTILATE_VALUESIZE="fb_value" # Follows ETC workload
MUTILATE_UPDATE_RATIO=0.0333

MUTILATE_AGENT_1_ALIAS="10.10.1.2"
MUTILATE_AGENT_2_ALIAS="10.10.1.3"
MUTILATE_AGENT_3_ALIAS="localhost"

MUTILATE_MASTER_THREADS=4
MUTILATE_MASTER_CLIENTS=64
# -Q/--measure_qps sets a small, separate “measurement” stream generated by the master.
# -Q $MUTILATE_MASTER_QPS keeps the master sending its own steady trickle 
# (spread over master threads/conns) used to sample latency with minimal client-side queuing.
MUTILATE_MASTER_QPS=1000
MUTILATE_MASTER_DEPTH=8

# Scan range (inclusive) and step for QPS. Adjust to suit your SLO search window.
SCAN_MIN_QPS=500000
SCAN_MAX_QPS=1000000
SCAN_STEP_QPS=100000

SYNC_DELAY=10

DATE_TAG=$(date '+%Y-%m-%d_%H-%M-%S')
LOG_DIR="scan_logs_xl170/run_${DATE_TAG}"
mkdir -p "$LOG_DIR"

SEPARATOR="------------------------------------------------------------"

# === SSH Helpers ===
ssh_with_retry() {
  local max_tries=10
  local count=0
  while ! ssh "$@"; do
    count=$((count+1))
    if [ "$count" -ge "$max_tries" ]; then
      echo "[!!] SSH failed after $count tries: $*" >&2
      return 1
    fi
    echo "[!] SSH failed. Retrying again ..."
    sleep 2
  done
}

scp_with_retry() {
  local max_tries=10
  local count=0
  while ! scp "$@"; do
    count=$((count+1))
    if [ "$count" -ge "$max_tries" ]; then
      echo "[!!] SCP failed after $count tries: $*" >&2
      return 1
    fi
    echo "[!] SCP failed. Retrying in 2s..."
    sleep 2
  done
}

echo "$SEPARATOR"
echo "[*] Opening persistent SSH connections..."
ssh -fN $SERVER_ALIAS
ssh -fN $CLIENT1_ALIAS
ssh -fN $CLIENT2_ALIAS
ssh -fN $CLIENT3_ALIAS

echo "$SEPARATOR"
echo "[*] Starting memcached on server..."
ssh_with_retry $SERVER_ALIAS <<EOF
  set -e
  mkdir -p logs_$DATE_TAG
  cd logs_$DATE_TAG

  sudo pkill memcached || true
  sleep 2

  nohup taskset -c $MEMCACHED_CORE_RANGE memcached -u nobody -l $MEMCACHED_IP -t $MEMCACHED_THREADS -c $MEMCACHED_MAX_CONNECTIONS > memcached_server.log 2>&1 &
  sleep 2
  sudo netstat -tuln | grep $MEMCACHED_IP || { echo "[!!] Memcached failed to start"; exit 1; }
EOF

echo "$SEPARATOR"
echo "[*] Sleeping for warm-up and sync (${SYNC_DELAY}s)..."
sleep $SYNC_DELAY

echo "$SEPARATOR"
echo "[*] Starting mutilate agents on clients..."
ssh_with_retry $CLIENT1_ALIAS <<EOF
  cd ~/mutilate
  sudo pkill mutilate || true
  nohup taskset -c $MUTILATE_AGENT_CORE_RANGE ./mutilate -T $MUTILATE_AGENT_THREADS -c $MUTILATE_AGENT_CLIENTS -d $MUTILATE_AGENT_DEPTH -A -i $MUTILATE_IADIST > /dev/null 2>&1 &
EOF

ssh_with_retry $CLIENT2_ALIAS <<EOF
  cd ~/mutilate
  sudo pkill mutilate || true
  nohup taskset -c $MUTILATE_AGENT_CORE_RANGE ./mutilate -T $MUTILATE_AGENT_THREADS -c $MUTILATE_AGENT_CLIENTS -d $MUTILATE_AGENT_DEPTH -A -i $MUTILATE_IADIST > /dev/null 2>&1 &
EOF

ssh_with_retry $CLIENT3_ALIAS <<EOF
  cd ~/mutilate
  sudo pkill mutilate || true
  nohup taskset -c $MUTILATE_AGENT_CORE_RANGE ./mutilate -T $MUTILATE_AGENT_THREADS -c $MUTILATE_AGENT_CLIENTS -d $MUTILATE_AGENT_DEPTH -A -i $MUTILATE_IADIST > /dev/null 2>&1 &
EOF

echo "$SEPARATOR"
echo "[*] Running mutilate scan on master (client3)..."
ssh_with_retry $CLIENT3_ALIAS <<EOF
  mkdir -p ~/mutilate/logs_$DATE_TAG
  cd ~/mutilate
  taskset -c 15-18 ./mutilate \
    -s $MEMCACHED_IP \
    -T $MUTILATE_MASTER_THREADS \
    -C $MUTILATE_MASTER_CLIENTS \
    -D $MUTILATE_MASTER_DEPTH \
    -Q $MUTILATE_MASTER_QPS \
    -a $MUTILATE_AGENT_1_ALIAS -a $MUTILATE_AGENT_2_ALIAS -a $MUTILATE_AGENT_3_ALIAS \
    -c $MUTILATE_AGENT_CLIENTS \
    -u $MUTILATE_UPDATE_RATIO \
    -K $MUTILATE_KEYSIZE \
    -V $MUTILATE_VALUESIZE \
    --scan ${SCAN_MIN_QPS}:${SCAN_MAX_QPS}:${SCAN_STEP_QPS} \
    -w $MUTILATE_WARMUP \
    -t $MUTILATE_TEST_DURATION \
    --noload \
    --iadist $MUTILATE_IADIST \
    > logs_$DATE_TAG/mutilate_scan.log
EOF

echo "$SEPARATOR"
echo "[*] Copying scan log back to local..."
scp_with_retry $CLIENT3_ALIAS:~/mutilate/logs_$DATE_TAG/mutilate_scan.log $LOG_DIR/

echo "$SEPARATOR"
echo "[*] Scan completed. Log saved to $LOG_DIR/mutilate_scan.log"
echo "$SEPARATOR"
